name: Build GKI 5.10.252
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          git clone --depth 1 --branch llvm-r416183 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 ~/aosp-clang
      - run: |
          export PATH="$HOME/aosp-clang/clang-r416183/bin:$PATH"
          make O=out ARCH=arm64 LLVM=1 CLANG_TRIPLE=aarch64-linux-gnu- gki_defconfig
          make O=out ARCH=arm64 LLVM=1 CLANG_TRIPLE=aarch64-linux-gnu- -j4 Image.gz
